name: msdfgen Build

on:
  workflow_dispatch:

jobs:
  msdf-gen-build:
    runs-on: ubuntu-22.04
    steps:

      - name: setup environment
        run: |
          sudo apt-get update
          sudo apt-get install cmake gcc make libtinyxml2-dev libpng-dev libfreetype-dev zlib1g-dev

      - uses: actions/checkout@v4
        with:
          repository: Yellow-Dog-Man/msdfgen
          submodules: true
          path: msdfgen

      - uses: actions/checkout@v4
        with:
          repository: ReinaS-64892/msdfgen-ydms-binary
          path: msdfgen-bin

      - name: build
        run: |
          mkdir build
          cd build
          cmake -S ../msdfgen -B ./ -DMSDFGEN_BUILD_STANDALONE=OFF -DMSDFGEN_BUILD_SHARED_LIBRARY=ON
          cmake --build ./

      - name: get date
        id: date
        run: |
          NOW=$(date +"%Y%m%d%H%M")
          echo "NowDate=${NOW}" >> $GITHUB_OUTPUT

      - name: git push tag
        env:
          tag: ${{ steps.date.outputs.NowDate }}
        run: |
          cd msdfgen-bin
          git config user.name  "GitHub Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag $tag
          git push
          git push origin $tag

      - name: Crate zip
        run: |
          zip -r msdf-gen-ydms-binary.zip ./build/out/libmsdfgen.so

      - name: CrateRelease
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.date.outputs.NowDate }}
          tag_name: ${{ steps.date.outputs.NowDate }}
          files: |
            msdf-gen-ydms-binary.zip
