name: msdfgen Build

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true
        description: commit hash or tag (ref)

jobs:
  msdf-gen-build:
    runs-on: ubuntu-22.04
    steps:

      - name: get cmake
        run: |
          sudo apt-get update
          sudo apt-get install cmake

      - uses: actions/checkout@v4
        with:
          repository: Chlumsky/msdfgen
          ref: ${{ inputs.ref }}
          submodules: true
          path: msdfgen

      - uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - name: setup vcpkg
        run: |
          cd vcpkg
          ./bootstrap-vcpkg.sh

      - name: build to export
        run: |
          cd msdfgen
          vcpkg install
          vcpkg export --zip --output-dir=../

      - name: debug
        run: |
          ls -alh
          ls msdfgen -alh
          ls vcpkg -alh
