name: msdfgen Build

on:
  workflow_dispatch:

jobs:
  msdf-gen-build:
    runs-on: ubuntu-22.04
    steps:

      - name: setup environment
        run: |
          sudo apt-get update
          sudo apt-get install cmake gcc make libtinyxml2-dev libpng-dev libfreetype-dev zlib1g-dev

      - uses: actions/checkout@v4
        with:
          repository: Yellow-Dog-Man/msdfgen
          submodules: true
          path: msdfgen

      # - uses: actions/checkout@v4
      #   with:
      #     repository: microsoft/vcpkg
      #     path: vcpkg

      # - name: setup vcpkg
      #   run: |
      #     cd vcpkg
      #     ./bootstrap-vcpkg.sh

      # - name: install packages
      #   run: |
      #     cd msdfgen
      #     vcpkg install

      - name: build
        run: |
          mkdir build
          cd build
          cmake -S ../msdfgen -B ./ -DMSDFGEN_BUILD_SHARED_LIBRARY=ON
          cmake --build ./

      - name: debug
        run: |
          ls -alh
          ls msdfgen -alh
          ls build -alh -R

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: msdfgen-build
      #     path: msdfgen-build.zip
